- name: check domain default password policy
  hosts: all
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - name: check default password policy
      win_shell: |
        Get-ADDefaultDomainPasswordPolicy
      register: default_domain_password_policy

    - debug:
        var: default_domain_password_policy

    - name: adjust password policy
      win_dsc:
        resource_name: xADDomainDefaultPasswordPolicy
        DomainName: "{{ dns_domain_name }}"
        ComplexityEnabled: False
        MinPasswordLength: 8
        PasswordHistoryCount: 10
        LockoutThreshold: 5

    - name: check default password policy
      win_shell: |
        Get-ADDefaultDomainPasswordPolicy
      register: default_domain_password_policy

    - debug:
        var: default_domain_password_policy